name: run-test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: install deps
        run: |
          sudo apt update
          sudo apt install lcov -y

      - name: verify tools
        run: |
          set -x
          gcc -v
          cmake --version
          lcov --version
          gcov --version

      - name: build
        run: |
          set -x
          mkdir build
          cd build
          cmake -G"Ninja" .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build .
      
      - name: test
        run: |
          set -x
          cd build
          ./app_test
          echo "measure coverage..."
          lcov -c -d . -o coverage.info  --ignore-errors mismatc
          genhtml -o coverage_report coverage.info
