name: run-test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: verify gcc
        run: gcc -v

      - name: verify cmake
        run: cmake --version

      # - name: setup python
      #   uses: actions/setup-python@v6
      #   with:
      #     python-version: 3.12

      # - name: install dependencies
      #   run: pip install -r requirements.txt

      # - name: run test
      #   run: pytest scripts/main.py
