name: run-test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: verify gcc
        run: |
          set -x
          gcc -v
          cmake --version

      - name: build
        run: |
          set -x
          mkdir build
          cd build
          cmake -G"Ninja" ..
          cmake --build .
      
      - name: test
        run: |
          set -x
          cd build
          ./app_test
